language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly

os:
  - linux

cache: cargo

env:
  matrix:
    - FEATURE=netlib
    - FEATURE=openblas

matrix:
  allow-failures:
    - rust: nightly

before_script:
  pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo test -- -vv --no-default-features --features=$FEATURE

after_success:
  - travis-cargo coveralls

addons:
  apt:
    sources:
      - kubuntu-backports

    packages:
      - cmake
      - gfortran
