language: rust
sudo: required
dist: trusty

rust:
  - stable
  - beta
  - nightly

os:
  - linux

cache: cargo

env:
  matrix:
    - FEATURE=netlib
    - FEATURE=openblas

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test -vv --no-default-features --features=$FEATURE

addons:
  apt:
    packages:
      - gfortran
